# -*- coding: utf-8 -*-
"""timeSeries&category_charts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFinP0sJkQO9NRq6Y65KdBL2Cg1KqC7w
"""

#TimeSeries_Project_SyntexHub
#Author: Yogitha Shekar
#Date: 2025-11-09
#Brief: Loads sales CSV, aggregates daily/monthly/quarterly, and creates 4 plots (line, monthly, grouped bar, pie).

from google.colab import files
print("A file upload dialog will open. Choose your CSV file (e.g., Superstore.csv).")
uploaded = files.upload()
print("Uploaded files:", list(uploaded.keys()))

import pandas as pd
csv_path = list(uploaded.keys())[0]  # automatically uses uploaded file name
df = pd.read_csv(csv_path)
print("File loaded successfully!\n")
print("Columns:", df.columns.tolist())
df.head()

# Rename columns to match our project expectation
df = df.rename(columns={
    'Order Date': 'date',
    'Category': 'category',
    'Sales': 'sales'
})

# Keep only the 3 relevant columns
df = df[['date', 'category', 'sales']]

# Convert date column to datetime format
df['date'] = pd.to_datetime(df['date'], errors='coerce')

# Drop rows where date or sales are missing
df = df.dropna(subset=['date', 'sales']).reset_index(drop=True)

print("Cleaned data preview:")
df.head()

print("Rows, Columns:", df.shape)
print("\nMissing values:\n", df.isna().sum())
print("\nDate range:", df['date'].min(), "to", df['date'].max())
print("\nCategories:\n", df['category'].value_counts())

# Daily total
daily_total = df.groupby('date', as_index=False)['sales'].sum()

# Monthly total
df['year_month'] = df['date'].dt.to_period('M')
monthly_total = df.groupby('year_month', as_index=False)['sales'].sum()
monthly_total['year_month'] = monthly_total['year_month'].dt.to_timestamp()

# Monthly by category
monthly_cat = df.groupby([pd.Grouper(key='date', freq='M'),'category'])['sales'].sum().reset_index()
monthly_cat['date'] = monthly_cat['date'].dt.to_period('M').dt.to_timestamp()

# Quarterly total
df['quarter'] = df['date'].dt.to_period('Q')
quarterly_total = df.groupby('quarter', as_index=False)['sales'].sum()
quarterly_total['quarter'] = quarterly_total['quarter'].dt.to_timestamp()

print("Aggregations complete.")
monthly_total.head()

import matplotlib.pyplot as plt
import os
os.makedirs('plots', exist_ok=True)

# 1) Daily total line chart
plt.figure(figsize=(12,4))
plt.plot(daily_total['date'], daily_total['sales'])
plt.title('Daily Total Sales')
plt.xlabel('Date'); plt.ylabel('Sales'); plt.tight_layout()
plt.savefig('plots/daily_total_sales.png', dpi=200)
plt.show()

# 2) Monthly total line chart
plt.figure(figsize=(10,4))
plt.plot(monthly_total['year_month'], monthly_total['sales'], marker='o')
plt.title('Monthly Total Sales')
plt.xlabel('Month'); plt.ylabel('Sales'); plt.tight_layout()
plt.savefig('plots/monthly_total_sales.png', dpi=200)
plt.show()

# 3) Grouped bar chart
monthly_pivot = monthly_cat.pivot(index='date', columns='category', values='sales').fillna(0)
ax = monthly_pivot.plot(kind='bar', figsize=(12,5), width=0.8)
ax.set_title('Monthly Sales by Category')
ax.set_xlabel('Month'); ax.set_ylabel('Sales')
plt.xticks(rotation=45, ha='right'); plt.tight_layout()
plt.savefig('plots/monthly_by_category_grouped.png', dpi=200)
plt.show()

# 4) Pie chart for category share
cat_share = df.groupby('category')['sales'].sum()
plt.figure(figsize=(6,6))
plt.pie(cat_share, labels=cat_share.index, autopct='%1.1f%%', startangle=90)
plt.title('Category Sales Share (Total Period)')
plt.tight_layout()
plt.savefig('plots/category_share_pie.png', dpi=200)
plt.show()

print("All plots saved inside 'plots' folder.")

from google.colab import files
for f in [
    'plots/daily_total_sales.png',
    'plots/monthly_total_sales.png',
    'plots/monthly_by_category_grouped.png',
    'plots/category_share_pie.png'
]:
    files.download(f)